export const carouseldata = [
  {
    projectID: 1,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 2,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 3,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },
  {
    projectID: 4,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 5,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 6,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },

  {
    projectID: 7,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 8,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 9,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },
  {
    projectID: 10,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 11,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 12,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },
  {
    projectID: 13,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 14,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 15,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },
  {
    projectID: 16,
    projectName: "SARIMOIRE",
    projectImage: "/Carousel/SarimoireImage.png",
    projectType: "Website",
  },
  {
    projectID: 17,
    projectName: "ROBINSONS MALL APP",
    projectImage: "/Carousel/RobinsonsMallImage.png",
    projectType: "Mobile App",
  },
  {
    projectID: 18,
    projectName: "ALFAMART",
    projectImage: "/Carousel/AlfamartImage.png",
    projectType: "Website and Mobile App",
  },
];
