/** DEFAULT */
const {
    SERVICES_DATA,
    SERVICES_MOTION_DIV
} = require("./Services");

const {
    ABOUT_US_SOCIALS_ICONS
} = require("./AboutUs");

const {
    PROJECTS_MOBILE_APPS,
    PROJECTS_WEBSITES,
    PROJECTS_CONTENT_MANAGEMENT_APP,
    PROJECTS_MOTION_DIV
} = require("./Projects");

const {
    ACCOMPLISHMENTS_BACKGROUND_IMAGES,
    ACCOMPLISHMENTS_APPFUTURA_ACHIEVEMENTS
} = require("./Accomplishments");

export {
    SERVICES_DATA,
    SERVICES_MOTION_DIV,
    ABOUT_US_SOCIALS_ICONS,
    PROJECTS_MOBILE_APPS,
    PROJECTS_WEBSITES,
    PROJECTS_CONTENT_MANAGEMENT_APP,
    PROJECTS_MOTION_DIV,
    ACCOMPLISHMENTS_BACKGROUND_IMAGES,
    ACCOMPLISHMENTS_APPFUTURA_ACHIEVEMENTS
}

